# Generated by Django 4.0 on 2021-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medpoint',
            fields=[
                ('medpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('medpt_name', models.TextField()),
                ('location_city', models.TextField()),
                ('location_district', models.TextField()),
                ('medpt_address', models.TextField()),
                ('medpt_phone', models.IntegerField()),
                ('medpt_hr_week', models.TimeField()),
                ('medpt_hr_sat', models.TimeField()),
                ('medpt_hr_hol', models.TimeField()),
                ('medpt_bogunso', models.TextField()),
                ('medpt_bogunso_ph', models.IntegerField()),
                ('medpt_notes', models.TextField()),
            ],
            options={
                'db_table': 'medpoint',
            },
        ),
    ]
