# Generated by Django 4.0 on 2021-12-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medpoint',
            name='medpt_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
