# Generated by Django 4.0 on 2022-01-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medpoint',
            name='medpt_bogunso_ph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medpoint',
            name='medpt_hr_hol',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medpoint',
            name='medpt_hr_sat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medpoint',
            name='medpt_hr_week',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medpoint',
            name='medpt_phone',
            field=models.TextField(),
        ),
    ]
