# Generated by Django 4.0 on 2021-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('user_name', models.TextField()),
                ('user_birthday', models.DateField()),
                ('user_sex', models.BooleanField()),
                ('user_phone', models.TextField(max_length=11)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.TextField()),
                ('user_vaccinated', models.BooleanField()),
                ('vaccine_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
