# Generated by Django 4.0 on 2021-12-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Vaccine',
            fields=[
                ('vaccine_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('innoculation_date', models.DateField()),
                ('vaccine_side_effect', models.TextField()),
            ],
            options={
                'db_table': 'user_vaccine',
            },
        ),
    ]
