# Generated by Django 4.0 on 2021-12-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine_Info',
        ),
        migrations.AlterField(
            model_name='user_vaccine',
            name='innoculation_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_vaccine',
            name='vaccine_type',
            field=models.TextField(),
        ),
    ]
