# Generated by Django 4.0 on 2021-12-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_sex',
            field=models.CharField(max_length=6),
        ),
    ]
