# Generated by Django 4.0 on 2021-12-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('msg_date', models.DateField()),
                ('msg_time', models.TimeField()),
                ('location_id', models.TextField()),
                ('location_name', models.TextField()),
                ('msg_content', models.TextField()),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
