# Generated by Django 4.0 on 2021-12-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
