# Generated by Django 4.0 on 2021-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12)),
                ('user_password', models.CharField(max_length=12)),
                ('user_name', models.TextField()),
                ('user_birthday', models.DateField()),
                ('user_sex', models.BooleanField()),
                ('user_phone', models.TextField(max_length=11)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.TextField()),
                ('user_vaccinated', models.BooleanField()),
                ('vaccine_type', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_Vaccine',
            fields=[
                ('vaccine_type', models.TextField(primary_key=True, serialize=False)),
                ('innoculation_date', models.DateField()),
                ('vaccine_side_effect', models.TextField()),
                ('undercond_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_vaccine',
            },
        ),
        migrations.CreateModel(
            name='Vaccine_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
