# Generated by Django 4.0 on 2021-12-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_vaccine_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_vaccine',
            name='vaccine_type',
            field=models.TextField(max_length=30),
        ),
    ]
