# Generated by Django 4.0 on 2021-12-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_vaccine_vaccine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_vaccine',
            name='innoculation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_vaccine',
            name='vaccine_type',
            field=models.TextField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
