# Generated by Django 4.0 on 2022-01-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.TextField()),
                ('news_link', models.TextField()),
                ('news_pub_date', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
